---
title: "Untitled"
output: html_document
date: "2024-11-19"
---

```{r}
library(rFIA)
library(tidyverse)
library(terra)
library(sf)
library(latex2exp)
```



```{r}
Piedmont.shp <- st_read("C:/Users/lagoodal/Desktop/Ecoregion Level 3 Full/nc_eco_l3.shp")
NC_FIA <- readFIA("C:/Users/lagoodal/Desktop/Dissertation Stuff/NC FIA")

TREE <- NC_FIA$TREE
COND <- NC_FIA$COND

rm(NC_FIA)

TREE$COUNTYCD <- sprintf("%03s", TREE$COUNTYCD)
TREE$PLOT <- sprintf("%05s", TREE$PLOT)
TREE$SUBP <- sprintf("%03s", TREE$SUBP)
TREE$TREE <- sprintf("%03s", TREE$TREE)
TREE <- TREE %>%
  mutate(GEOID = paste0(COUNTYCD, PLOT),
         TREEID = paste0(COUNTYCD, PLOT, SUBP, TREE))

COND$COUNTYCD <- sprintf("%03s", COND$COUNTYCD)
COND$PLOT <- sprintf("%05s", COND$PLOT)
COND <- COND %>%
  mutate(GEOID = paste0(COUNTYCD, PLOT))

TREE <- TREE %>%
  filter(SPGRPCD < 50,
         INVYR %in% 2000:9000,
         SPCD %in% c(68,110,121,131,132,221,316,403,407,409,544,611,621,693,694,802,806,812,819,820,824,827,832,833,835,837)) %>%
  mutate(dummySPGRPCD = ifelse(SPGRPCD %in% 1:24, "Softwoods", "Hardwoods"))

TREE$dummySPGRPCD <- ifelse(TREE$SPCD == 802 | TREE$SPCD == 812 | TREE$SPCD == 820 | TREE$SPCD == 827 | TREE$SPCD == 833, "Mesic Oaks", TREE$dummySPGRPCD)
TREE$dummySPGRPCD <- ifelse(TREE$SPCD == 806 | TREE$SPCD == 819 | TREE$SPCD == 824 | TREE$SPCD == 832 | TREE$SPCD == 835 | TREE$SPCD == 837, "Xeric Oaks", TREE$dummySPGRPCD)
TREE$dummySPGRPCD <- ifelse(TREE$SPCD == 221, "Cypress", TREE$dummySPGRPCD)
# TREE$dummySPGRPCD <- ifelse(TREE$SPCD == 802, "White Oak", TREE$dummySPGRPCD)

treeTable <- full_join(TREE, COND, by = c("GEOID", "COUNTYCD", "PLT_CN", "INVYR", "STATECD", "UNITCD", "PLOT", "CONDID"))

treeTable <- treeTable %>%
  filter(INVYR < 9000,
         SPCD < 998)

treeTable <- treeTable[,c("GEOID", "TREEID", "CARBON_AG", "STDAGE", "INVYR", "SPCD", "dummySPGRPCD", "TPA_UNADJ")] %>%
  unique()

treeTable <- treeTable %>%
  mutate(BIOMASS = CARBON_AG * 2,
         BIOMASS_AC = BIOMASS * TPA_UNADJ,
         BIOMASS_gm2 = BIOMASS_AC * 0.1121)


treeTable <- treeTable %>%
  mutate(binnedAGE = ifelse(STDAGE %in% 1:10, 10,
                            ifelse(STDAGE %in% 11:20, 20,
                                   ifelse(STDAGE %in% 21:30, 30,
                                          ifelse(STDAGE %in% 31:40, 40,
                                                 ifelse(STDAGE %in% 41:50, 50,
                                                        ifelse(STDAGE %in% 51:60, 60,
                                                               ifelse(STDAGE %in% 61:70, 70,
                                                                      ifelse(STDAGE %in% 71:80, 80,
                                                                             ifelse(STDAGE %in% 81:90, 90,
                                                                                    ifelse(STDAGE %in% 91:100, 100,
                                                                                           ifelse(STDAGE %in% 101:110, 110,
                                                                                                  ifelse(STDAGE %in% 111:120, 120,
                                                                                                         ifelse(STDAGE %in% 121:130, 130,
                                                                                                                ifelse(STDAGE %in% 131:140, 140,
                                                                                                                       ifelse(STDAGE %in% 141:150, 150, 160))))))))))))))))

treeTable <- treeTable %>%
  group_by(binnedAGE, dummySPGRPCD) %>%
  filter(quantile(BIOMASS_gm2, 0.75, na.rm = T) < BIOMASS_gm2,
         binnedAGE < 101)




```


# Softwoods

```{r}
mapIC <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/treeMapTC.tif")
ecoregions <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/Ecoregions1.tif")
plot(mapIC)
mapCodes <- read_csv("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/MapCodeDf.csv")

# PITA
PITAcodes <- mapCodes %>%
  filter(CohortAge == 10 & SpeciesName == "PITA")
non_matching_mapcodes <- anti_join(mapCodes, PITAcodes, by = "MapCode")
matching_mapcodes <- inner_join(mapCodes, PITAcodes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
cell_indices <- which(values(mapIC) == 60453)
row_col_indices <- rowColFromCell(mapIC, cell_indices)
row_col_indices
values(ecoregions) <- 0
for (i in 1:nrow(row_col_indices)) {
  ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
}

# # PIEC2
# PIEC2codes <- mapCodes %>%
#   filter(CohortAge == 30 & SpeciesName == "PIEC2")
# non_matching_mapcodes <- anti_join(mapCodes, PIEC2codes, by = "MapCode")
# matching_mapcodes <- inner_join(mapCodes, PIEC2codes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
# mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
# cell_indices <- which(values(mapIC) == 48834)
# row_col_indices <- rowColFromCell(mapIC, cell_indices)
# # row_col_indices
# for (i in 1:nrow(row_col_indices)) {
#   ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
# }

# # PIVI2
# PIVI2codes <- mapCodes %>%
#   filter(CohortAge == 10 & SpeciesName == "PIVI2")
# non_matching_mapcodes <- anti_join(mapCodes, PIVI2codes, by = "MapCode")
# matching_mapcodes <- inner_join(mapCodes, PIVI2codes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
# mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
# cell_indices <- which(values(mapIC) == 49832)
# row_col_indices <- rowColFromCell(mapIC, cell_indices)
# # row_col_indices
# for (i in 1:nrow(row_col_indices)) {
#   ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
# }

# PIPA2
PIPA2codes <- mapCodes %>%
  filter(CohortAge == 20 & SpeciesName == "PIPA2")
non_matching_mapcodes <- anti_join(mapCodes, PIPA2codes, by = "MapCode")
matching_mapcodes <- inner_join(mapCodes, PIPA2codes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
cell_indices <- which(values(mapIC) == 59530)
row_col_indices <- rowColFromCell(mapIC, cell_indices)
# row_col_indices
for (i in 1:nrow(row_col_indices)) {
  ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
}


writeRaster(ecoregions,
            filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/softwoodsEcoregion.tif",
            datatype = "INT1U",
            NAflag = NA,
            overwrite = TRUE)
```


```{r}
ggplot(treeTable %>% filter(dummySPGRPCD %in% c("Softwoods")), aes(x = as.factor(binnedAGE), y = BIOMASS_gm2)) +
  geom_boxplot() +
  geom_point(alpha = 0) +
  geom_smooth(method = "loess", aes(group = 1)) +
  theme_classic() +
  ylim(0,5100) +
  facet_wrap(~dummySPGRPCD) +
  xlab("Stand Age") +
  ylab(TeX("AGB $(\\g/m^2)$")) +
  geom_point(data = data.frame(binnedAGE = 10, BIOMASS_gm2 = 288, dummySPGRPCD = "Softwoods"), col = "red") + # PITA
  geom_point(data = data.frame(binnedAGE = 20, BIOMASS_gm2 = 439, dummySPGRPCD = "Softwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 576, dummySPGRPCD = "Softwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 627, dummySPGRPCD = "Softwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 822, dummySPGRPCD = "Softwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 952, dummySPGRPCD = "Softwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 1044, dummySPGRPCD = "Softwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 1139, dummySPGRPCD = "Softwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 1232, dummySPGRPCD = "Softwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 1317, dummySPGRPCD = "Softwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 10, BIOMASS_gm2 = 199, dummySPGRPCD = "Softwoods"), col = "blue") + # PIPA2
  geom_point(data = data.frame(binnedAGE = 20, BIOMASS_gm2 = 371, dummySPGRPCD = "Softwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 520, dummySPGRPCD = "Softwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 578, dummySPGRPCD = "Softwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 714, dummySPGRPCD = "Softwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 853, dummySPGRPCD = "Softwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 944, dummySPGRPCD = "Softwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 1040, dummySPGRPCD = "Softwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 1137, dummySPGRPCD = "Softwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 1236, dummySPGRPCD = "Softwoods"), col = "blue")
```

# Hardwoods

```{r}
mapIC <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/treeMapTC.tif")
ecoregions <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/Ecoregions1.tif")
plot(mapIC)
mapCodes <- read_csv("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/MapCodeDf.csv")

# ACRU & LIST2
ACRUcodes <- mapCodes %>%
  filter(CohortAge == 10 & SpeciesName == "ACRU")
non_matching_mapcodes <- anti_join(mapCodes, ACRUcodes, by = "MapCode")
matching_mapcodes <- inner_join(mapCodes, ACRUcodes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
cell_indices <- which(values(mapIC) == 59721)
row_col_indices <- rowColFromCell(mapIC, cell_indices)
values(ecoregions) <- 0
for (i in 1:nrow(row_col_indices)) {
  ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
}


# LITU
LITUcodes <- mapCodes %>%
  filter(CohortAge == 10 & SpeciesName == "LITU")
non_matching_mapcodes <- anti_join(mapCodes, LITUcodes, by = "MapCode")
matching_mapcodes <- inner_join(mapCodes, LITUcodes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
cell_indices <- which(values(mapIC) == 49109)
row_col_indices <- rowColFromCell(mapIC, cell_indices)
for (i in 1:nrow(row_col_indices)) {
  ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
}

mapCodes %>% filter(MapCode == 49109)

writeRaster(ecoregions,
            filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/hardwoodsEcoregion.tif",
            datatype = "INT1U",
            NAflag = NA,
            overwrite = TRUE)

```



```{r}
ggplot(treeTable %>% filter(dummySPGRPCD %in% c("Hardwoods")), aes(x = as.factor(binnedAGE), y = BIOMASS_gm2)) +
  geom_boxplot() +
  geom_point(alpha = 0) +
  geom_smooth(method = "loess", aes(group = 1)) +
  theme_classic() +
  ylim(0,5100) +
  facet_wrap(~dummySPGRPCD) +
  xlab("Stand Age") +
  ylab(TeX("AGB $(\\g/m^2)$")) +
  geom_point(data = data.frame(binnedAGE = 10, BIOMASS_gm2 = 233, dummySPGRPCD = "Hardwoods"), col = "red") + # ACRU
  geom_point(data = data.frame(binnedAGE = 20, BIOMASS_gm2 = 351, dummySPGRPCD = "Hardwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 472, dummySPGRPCD = "Hardwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 518, dummySPGRPCD = "Hardwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 605, dummySPGRPCD = "Hardwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 671, dummySPGRPCD = "Hardwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 695, dummySPGRPCD = "Hardwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 706, dummySPGRPCD = "Hardwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 697, dummySPGRPCD = "Hardwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 650, dummySPGRPCD = "Hardwoods"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 809, dummySPGRPCD = "Hardwoods"), col = "blue") + # LIST2
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 846, dummySPGRPCD = "Hardwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 964, dummySPGRPCD = "Hardwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 1033, dummySPGRPCD = "Hardwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 1221, dummySPGRPCD = "Hardwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 1451, dummySPGRPCD = "Hardwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 1610, dummySPGRPCD = "Hardwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 1770, dummySPGRPCD = "Hardwoods"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 10, BIOMASS_gm2 = 199, dummySPGRPCD = "Hardwoods"), col = "green") + # LITU
  geom_point(data = data.frame(binnedAGE = 20, BIOMASS_gm2 = 371, dummySPGRPCD = "Hardwoods"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 520, dummySPGRPCD = "Hardwoods"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 578, dummySPGRPCD = "Hardwoods"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 714, dummySPGRPCD = "Hardwoods"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 853, dummySPGRPCD = "Hardwoods"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 944, dummySPGRPCD = "Hardwoods"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 1040, dummySPGRPCD = "Hardwoods"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 1137, dummySPGRPCD = "Hardwoods"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 1236, dummySPGRPCD = "Hardwoods"), col = "green")
```

# Oaks

```{r}
mapIC <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/treeMapTC.tif")
ecoregions <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/Ecoregions1.tif")
plot(mapIC)
mapCodes <- read_csv("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/MapCodeDf.csv")

# QUAL
QUALcodes <- mapCodes %>%
  filter(CohortAge == 10 & SpeciesName == "QUAL")
non_matching_mapcodes <- anti_join(mapCodes, QUALcodes, by = "MapCode")
matching_mapcodes <- inner_join(mapCodes, QUALcodes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
cell_indices <- which(values(mapIC) == 49573)
row_col_indices <- rowColFromCell(mapIC, cell_indices)
values(ecoregions) <- 0
for (i in 1:nrow(row_col_indices)) {
  ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
}

# QURU
QURUcodes <- mapCodes %>%
  filter(CohortAge == 10 & SpeciesName == "QURU")
non_matching_mapcodes <- anti_join(mapCodes, QURUcodes, by = "MapCode")
matching_mapcodes <- inner_join(mapCodes, QURUcodes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
cell_indices <- which(values(mapIC) == 48768)
row_col_indices <- rowColFromCell(mapIC, cell_indices)
for (i in 1:nrow(row_col_indices)) {
  ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
}

# # QUCO2
# QUCO2codes <- mapCodes %>%
#   filter(CohortAge == 10 & SpeciesName == "QUCO2")
# non_matching_mapcodes <- anti_join(mapCodes, QUCO2codes, by = "MapCode")
# matching_mapcodes <- inner_join(mapCodes, QUCO2codes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
# mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
# cell_indices <- which(values(mapIC) == 49033)
# row_col_indices <- rowColFromCell(mapIC, cell_indices)
# for (i in 1:nrow(row_col_indices)) {
#   ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
# }
# 
# # QUST
# QUSTcodes <- mapCodes %>%
#   filter(CohortAge == 10 & SpeciesName == "QUST")
# non_matching_mapcodes <- anti_join(mapCodes, QUSTcodes, by = "MapCode")
# matching_mapcodes <- inner_join(mapCodes, QUSTcodes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
# mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
# cell_indices <- which(values(mapIC) == 49902)
# row_col_indices <- rowColFromCell(mapIC, cell_indices)
# for (i in 1:nrow(row_col_indices)) {
#   ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
# }

writeRaster(ecoregions,
            filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/oaksEcoregion.tif",
            datatype = "INT1U",
            NAflag = NA,
            overwrite = TRUE)
```


```{r}
ggplot(treeTable %>% filter(dummySPGRPCD %in% c("Mesic Oaks", "Xeric Oaks")), aes(x = as.factor(binnedAGE), y = BIOMASS_gm2)) +
  geom_boxplot() +
  geom_point(alpha = 0) +
  geom_smooth(method = "loess", aes(group = 1)) +
  theme_classic() +
  ylim(0,5100) +
  facet_wrap(~dummySPGRPCD) +
  xlab("Stand Age") +
  ylab(TeX("AGB $(\\g/m^2)$")) +
  geom_point(data = data.frame(binnedAGE = 10, BIOMASS_gm2 = 14, dummySPGRPCD = "Mesic Oaks"), col = "red") + # QURU
  geom_point(data = data.frame(binnedAGE = 20, BIOMASS_gm2 = 287, dummySPGRPCD = "Mesic Oaks"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 719, dummySPGRPCD = "Mesic Oaks"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 1116, dummySPGRPCD = "Mesic Oaks"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 1582, dummySPGRPCD = "Mesic Oaks"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 2025, dummySPGRPCD = "Mesic Oaks"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 2340, dummySPGRPCD = "Mesic Oaks"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 2583, dummySPGRPCD = "Mesic Oaks"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 2765, dummySPGRPCD = "Mesic Oaks"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 2900, dummySPGRPCD = "Mesic Oaks"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 10, BIOMASS_gm2 = 18, dummySPGRPCD = "Mesic Oaks"), col = "blue") + # QUAL
  geom_point(data = data.frame(binnedAGE = 20, BIOMASS_gm2 = 241, dummySPGRPCD = "Mesic Oaks"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 571, dummySPGRPCD = "Mesic Oaks"), col = "blue") + 
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 786, dummySPGRPCD = "Mesic Oaks"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 1095, dummySPGRPCD = "Mesic Oaks"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 1424, dummySPGRPCD = "Mesic Oaks"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 1612, dummySPGRPCD = "Mesic Oaks"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 1753, dummySPGRPCD = "Mesic Oaks"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 1857, dummySPGRPCD = "Mesic Oaks"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 1933, dummySPGRPCD = "Mesic Oaks"), col = "blue") +
  geom_point(data = data.frame(binnedAGE = 10, BIOMASS_gm2 = 36, dummySPGRPCD = "Xeric Oaks"), col = "green") + # QUCO2
  geom_point(data = data.frame(binnedAGE = 20, BIOMASS_gm2 = 224, dummySPGRPCD = "Xeric Oaks"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 449, dummySPGRPCD = "Xeric Oaks"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 561, dummySPGRPCD = "Xeric Oaks"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 730, dummySPGRPCD = "Xeric Oaks"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 913, dummySPGRPCD = "Xeric Oaks"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 1015, dummySPGRPCD = "Xeric Oaks"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 1099, dummySPGRPCD = "Xeric Oaks"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 1166, dummySPGRPCD = "Xeric Oaks"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 1218, dummySPGRPCD = "Xeric Oaks"), col = "green") +
  geom_point(data = data.frame(binnedAGE = 10, BIOMASS_gm2 = 6, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue") + # QUST
  geom_point(data = data.frame(binnedAGE = 20, BIOMASS_gm2 = 116, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 272, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue") +
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 375, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 527, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 687, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 774, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 841, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 890, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 926, dummySPGRPCD = "Xeric Oaks"), col = "dodgerblue")

```

# Cypress

```{r}
mapIC <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/treeMapTC.tif")
ecoregions <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/Ecoregions1.tif")
plot(mapIC)
mapCodes <- read_csv("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/MapCodeDf.csv")

# TADI2
TADI2codes <- mapCodes %>%
  filter(CohortAge == 10 & SpeciesName == "TADI2")
non_matching_mapcodes <- anti_join(mapCodes, TADI2codes, by = "MapCode")
matching_mapcodes <- inner_join(mapCodes, TADI2codes, by = c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))
mapCodes <- bind_rows(non_matching_mapcodes, matching_mapcodes)
cell_indices <- which(values(mapIC) == 60210)
row_col_indices <- rowColFromCell(mapIC, cell_indices)
values(ecoregions) <- 0
for (i in 1:nrow(row_col_indices)) {
  ecoregions[row_col_indices[,1][i], row_col_indices[,2][i]] <- 1
}

writeRaster(ecoregions,
            filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/cypressEcoregion.tif",
            datatype = "INT1U",
            NAflag = NA,
            overwrite = TRUE)
```


```{r}
ggplot(treeTable %>% filter(dummySPGRPCD %in% c("Cypress")), aes(x = as.factor(binnedAGE), y = BIOMASS_gm2)) +
  geom_boxplot() +
  geom_point(alpha = 0) +
  geom_smooth(method = "loess", aes(group = 1)) +
  theme_classic() +
  ylim(0,5100) +
  facet_wrap(~dummySPGRPCD) +
  xlab("Stand Age") +
  ylab(TeX("AGB $(\\g/m^2)$")) +
  geom_point(data = data.frame(binnedAGE = 10, BIOMASS_gm2 = 20, dummySPGRPCD = "Cypress"), col = "red") + # TADI2
  geom_point(data = data.frame(binnedAGE = 20, BIOMASS_gm2 = 187, dummySPGRPCD = "Cypress"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 30, BIOMASS_gm2 = 346, dummySPGRPCD = "Cypress"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 40, BIOMASS_gm2 = 463, dummySPGRPCD = "Cypress"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 50, BIOMASS_gm2 = 648, dummySPGRPCD = "Cypress"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 60, BIOMASS_gm2 = 856, dummySPGRPCD = "Cypress"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 70, BIOMASS_gm2 = 1026, dummySPGRPCD = "Cypress"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 80, BIOMASS_gm2 = 1190, dummySPGRPCD = "Cypress"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 90, BIOMASS_gm2 = 1340, dummySPGRPCD = "Cypress"), col = "red") +
  geom_point(data = data.frame(binnedAGE = 100, BIOMASS_gm2 = 1475, dummySPGRPCD = "Cypress"), col = "red")
```










