---
title: "Untitled"
output: pdf_document
date: "2024-11-13"
---


```{r}
library(tidyverse)
library(terra)
library(sf)
```

# Management Areas

```{r}
# Read in counties shapefile and filter to the 3 counties of interest
countiesNC <- st_read("C:/Users/lagoodal/Desktop/nc_eco_l3/North_Carolina_State_and_County_Boundary_Polygons.shp")
threeCounties <- countiesNC %>% filter(County %in% c("Anson", "Montgomery", "Richmond")) %>%
  st_as_sf(.) %>%
  st_transform(., crs = "EPSG:26917")

# Select just the County column
threeCounties <- threeCounties[2]

# Create a new column for LANDIS management areas
threeCounties <- threeCounties %>%
  mutate(ID = ifelse(.$County == "Anson", 1,
                     ifelse(.$County == "Richmond", 2, 3)))

# Rasterize to the template raster
templateRaster <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Three_Counties_Rasters/templateRaster.tif")
ManagementAreaRast <- rasterize(threeCounties, templateRaster, field = "ID")
plot(ManagementAreaRast)

writeRaster(ManagementAreaRast,
            filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Three_Counties_Rasters/Harvest/ManagementAreas.tif",
            datatype = "INT1U",
            NAflag = 0,
            overwrite = TRUE)
```


