---
title: "Stands Map"
output: pdf_document
date: "2024-11-12"
---

```{r}
library(tidyverse)
library(terra)
library(sf)
```



```{r}
# Read in 3 counties shapefile and the HUC 12 watershed of NC
threeCounties.Shp <- st_read("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Three_Counties_Rasters/Shapefile/threeCounties.shp")
watershedsHUC <- st_read("C:/Users/lagoodal/Desktop/All Raster Layers/HUC 8 Watersheds/Shape/WBDHU12.shp")

# Project the shapefile to the watershed shapefile, then crop and mask
threeCounties.Shp <- threeCounties.Shp %>%
  st_transform(., crs = crs(watershedsHUC))
watershedsHUC <- watershedsHUC %>%
  st_crop(., threeCounties.Shp) %>%
  st_intersection(., threeCounties.Shp)

# Add in county borders to act as extra stand divisions which will then
# match our future management areas
countiesNC <- st_read("C:/Users/lagoodal/Desktop/nc_eco_l3/North_Carolina_State_and_County_Boundary_Polygons.shp")
threeCounties <- countiesNC %>%
  st_as_sf() %>%
  filter(County %in% c("Anson", "Montgomery", "Richmond")) %>%
  st_transform(., crs = crs(watershedsHUC))
watershedsHUC <- watershedsHUC %>% st_intersection(., threeCounties)


plot(watershedsHUC[12])
plot(threeCounties[2])

# st_write(threeCounties[2],
#          dsn = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Shapefiles/ThreeCounties.shp")
```



```{r}
# Create a shapefile that has the major roads in the 3 county region, which is
# also bounded by the 3 counties border
roadsNC <- st_read("C:/Users/lagoodal/Desktop/Dissertation Stuff/Data/County Roads/State_Maintained_Roads.shp")
roadsNC <- roadsNC[2]
threeCounties.Shp <- threeCounties.Shp %>% st_transform(., crs = crs(roadsNC))
intersection_result <- st_intersection(roadsNC, threeCounties.Shp)
plot(intersection_result)


# st_write(intersection_result[2],
#          dsn = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Shapefiles/roadsTC.shp")

```


# Bring back from QGIS

```{r}
ManagementAreaRast <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Harvest/ManagementAreas.tif")
standsTC <- st_read("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Shapefiles/standsTC.shp") %>%
  st_transform(., crs = "EPSG:26917") %>%
  mutate(StandID = 1:nrow(.))
plot(standsTC[7])

templateRaster <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Three_Counties_Rasters/templateRaster.tif")

standRast <- rasterize(standsTC, templateRaster, field = "StandID")

# I need to edit some of the stands because they are straddling two different MAs
# Stand 1258
x <- ifel(standRast == 1258, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 3)
standRast[562,482] <- 2
standRast[564,453] <- 2

# Stand 1259
x <- ifel(standRast == 1259, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 2)
standRast[564,470] <- 3

plot(standRast)
plot(ManagementAreaRast)

writeRaster(standRast,
            filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Harvest/standRast.tif",
            NAflag = 0,
            datatype = "INT4S",
            overwrite = TRUE)


# There are some discrepancies between the stand raster and the management area raster.
# ManagementAreaRast had a few more active cells than standRast. I will sort those out now

maskStand <- !is.na(standRast)
ManagementAreaRast[!maskStand] <- NA

writeRaster(ManagementAreaRast,
            filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Harvest/ManagementAreas.tif",
            datatype = "INT1U",
            NAflag = 0,
            overwrite = TRUE)

# Now some more stands are straddling two management areas
# Stand 1291
x <- ifel(standRast == 1291, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 3)
ManagementAreaRast[526,811] <- 2
ManagementAreaRast[527,817] <- 2

# Stand 1280
x <- ifel(standRast == 1280, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 3)
ManagementAreaRast[528,652] <- 2
ManagementAreaRast[528,671] <- 2
ManagementAreaRast[529,625] <- 2
ManagementAreaRast[529,674] <- 2
ManagementAreaRast[530,628] <- 2

# Stand 1283
x <- ifel(standRast == 1283, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 2)
ManagementAreaRast[528,754] <- 3
ManagementAreaRast[531,750] <- 3

# Stand 1282
x <- ifel(standRast == 1282, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 3)
ManagementAreaRast[528,762] <- 2
ManagementAreaRast[529,764] <- 2

# Stand 1345
x <- ifel(standRast == 1345, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 3)
ManagementAreaRast[530,704] <- 2
ManagementAreaRast[534,728] <- 2

# Stand 1298
x <- ifel(standRast == 1298, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 2)
ManagementAreaRast[521,606] <- 3
ManagementAreaRast[532,589] <- 3
ManagementAreaRast[536,583] <- 3

# Stand 1301
x <- ifel(standRast == 1301, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 3)
ManagementAreaRast[557,877] <- 2
ManagementAreaRast[557,878] <- 2
ManagementAreaRast[557,879] <- 2

# Stand 1237
x <- ifel(standRast == 1237, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 2)
ManagementAreaRast[564,434] <- 3

# Stand 1184
x <- ifel(standRast == 1184, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 3)
ManagementAreaRast[576,416] <- 2
ManagementAreaRast[578,412] <- 2
ManagementAreaRast[583,406] <- 2

# Stand 1153
x <- ifel(standRast == 1153, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 3)
ManagementAreaRast[591,392] <- 2

# Stand 3
x <- ifel(standRast == 3, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 2)
ManagementAreaRast[564,470] <- 1

# Stand 2
x <- ifel(standRast == 2, 1, NA)
stack <- c(x, ManagementAreaRast)
df <- as.data.frame(stack, cell = TRUE) %>%
  filter(StandID == 1) %>%
  mutate(row = (cell - 1) %/% 1121 + 1,
         col = (cell - 1) %% 1121 + 1)
df %>% filter(ID == 3)
ManagementAreaRast[562,482] <- 1
ManagementAreaRast[564,453] <- 1


# writeRaster(ManagementAreaRast,
#             filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Harvest/ManagementAreas.tif",
#             datatype = "INT1U",
#             NAflag = 0,
#             overwrite = TRUE)
```







